# Generated by Django 6.0.7 on 2026-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_max_loan_allowed_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_loan_allowed',
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
