# Generated by Django 6.0.7 on 2026-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_max_loan_allowed_profile_loan_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loan_allowed',
        ),
        migrations.AddField(
            model_name='profile',
            name='max_loan_allowed',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
