# Generated by Django 6.0.7 on 2026-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'Estados Unidos'), ('GB', 'Reino Unido'), ('FR', 'França'), ('DE', 'Alemanha'), ('ES', 'Espanha'), ('IT', 'Itália'), ('RU', 'Rússia'), ('JP', 'Japão'), ('IN', 'Índia'), ('BR', 'Brasil')], max_length=2, null=True)),
            ],
        ),
    ]
