# Generated by Django 6.0.7 on 2026-07-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_copies', models.PositiveIntegerField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='books', to='authors.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='genres.genre')),
            ],
        ),
    ]
