# Generated by Django 6.0.7 on 2026-07-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_book_alter_loan_user'),
        ('users', '0004_remove_profile_loan_allowed_profile_max_loan_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.profile'),
        ),
    ]
